Repository EC-Nordbund/ec-verwaltungs-app, pull requests merged in 2018-08, with the labels that each got.

#107 Show lesezeichen as list
  src/plugins/lesezeichen/showLesezeichen.vue
Labels: enhancement

#112 Redesign loading screen
  electron/src/main/main.js
  public/ec-logo-without-bg-48.png
  public/ec-nordbund-logo.png
  public/loading.css
  public/loading.html
Labels: Idee, enhancement

#115 [UX] Select all bookmarks at once
  src/plugins/lesezeichen/showLesezeichen.vue
Labels: enhancement

#119 [UX] Geschlechter spezifisch gefärbte Radio-Buttons
  src/plugins/lib/formElements/inputs/radio.ts
  src/plugins/lib_extension/radioGroups/geschlecht.ts
Labels: enhancement

#118 [Fix] init value at radio and checkboxes
  src/plugins/lib_extension/radioGroups/geschlecht.ts
  src/plugins/lib_extension/radioGroups/position.ts
  src/plugins/lib_extension/radioGroups/type.ts
Labels: bug, question

#121 [Fix] unique keys for bookmarks
  src/plugins/lesezeichen/showLesezeichen.vue
Labels: bug

#123 [Fix] delete multiple bookmarks
  src/plugins/lesezeichen/showLesezeichen.vue
Labels: bug, enhancement

#126 (API) Pagination API in Table
  package.json
  src/plugins/lib/design/table.vue
  yarn.lock
Labels: enhancement

#131 [Fix] init value at selects
  src/views/personen/details.vue
Labels: bug, enhancement, question

#137 [Fix] Negative Logout countdown after standby
  src/App.vue
Labels: bug, enhancement, question

#127 Admin und profil
  LICENSE-LOSUNG
  package.json
  src/graphql/index.ts
  src/plugins/config/nav.config.ts
  src/plugins/formConfig/index.ts
  src/plugins/lib/componentLib.ts
  src/plugins/lib/formElements/inputs/checkbox.vue
  src/plugins/lib_extension/componentLib_extension.ts
  src/plugins/lib_extension/selects/userGroupSelect.ts
  src/plugins/router/routes/index.ts
  src/plugins/widgets/widgets/losungen.vue
  src/views/Admin.vue
  src/views/Profil.vue
  src/views/arbeitskreise/details.vue
  src/views/personen/details.vue
  yarn.lock
Labels: bug, enhancement

#138 Buildfix
  src/App.vue
Labels: bug

#141 Verschiedene dinge
  src/main.ts
  src/plugins/lib/formElements/formDialog/element.ts
  src/plugins/widgets/widgets/alert.vue
  src/plugins/wrapper.vue
  src/views/Admin.vue
  src/views/Impressum.vue
  src/views/Profil.vue
  src/views/anmeldungen/details.vue
  src/views/veranstaltungen/details.vue
  src/views/veranstaltungen/liste.vue
Labels: enhancement
