Repository EC-Nordbund/ec-verwaltungs-app, pull requests merged in 2018-07, with the labels that each got.

#68 adding CapsLockInfo bei Login
  public/losung.png
  src/Login.vue
  src/plugins/widgets/widgets/losungen.vue
Labels: enhancement

#69 UX (some first todos of issue)
  src/App.vue
  src/Login.vue
  src/views/Admin.vue
Labels: enhancement

#71 update Vuetify, upgrade deps
  electron/yarn.lock
  package.json
  yarn.lock
Labels: enhancement

#73 verbesserung Login autoFocus + Version to 0.1.6
  electron/package.json
  package.json
  src/Login.vue
  src/plugins/design/vuetify.ts
  src/plugins/lib/design/table.vue
  src/plugins/widgets/index.ts
  src/plugins/widgets/widgets/alert.vue
  src/plugins/widgets/widgets/losungen.vue
  src/views/Home.vue
  src/views/veranstaltungen/details.vue
Labels: enhancement

#80 Update Home.vue
  src/views/Home.vue
Labels: good first issue

#82 Automatisches öffnen des Nav-Drawers
  src/App.vue
Labels: enhancement

#81 [UX] Route Animations
  public/style.css
  src/plugins/router/routes/index.ts
  src/plugins/router/routes/router.vue
Labels: enhancement

#85 Adding better Routing - + Lesezeichen
  docs/.vuepress/config.js
  electron/package.json
  electron/src/main/main.dev.js
  electron/src/main/main.js
  electron/yarn.lock
  package.json
  public/index.html
  src/App.vue
  src/Login.vue
  src/baseComponents/reloader.ts
  src/graphql/index.ts
  src/main.ts
  src/plugins/auth.ts
  src/plugins/formConfig/index.ts
  src/plugins/lesezeichen/addLesezeichen.vue
  src/plugins/lesezeichen/lesezeichen.ts
  src/plugins/lesezeichen/showLesezeichen.vue
  src/plugins/lib/buttons/router-back.ts
  src/plugins/lib/componentLib.ts
  src/plugins/lib/design/table.vue
  src/plugins/lib/formElements/formDialog/form.ts
  src/plugins/lib/password.vue
  src/plugins/lib_extension/componentLib_extension.ts
  src/plugins/router/router.ts
  src/plugins/router/routes/index.ts
  src/plugins/router/routes/router.vue
  src/plugins/widgets/widgetElement.vue
  src/plugins/widgets/widgets/losungen.vue
  src/plugins/wrapper.vue
  src/plugins/xButton/btn.vue
  src/plugins/xButton/logic.ts
  src/views/Admin.vue
  src/views/Drucken.vue
  src/views/Impressum.vue
  src/views/arbeitskreise/details.vue
  src/views/arbeitskreise/liste.vue
  src/views/personen/details.vue
  src/views/personen/liste.vue
  src/views/unterkünfte/details.vue
  src/views/veranstaltungen/details.vue
  src/views/verteiler/details.vue
  src/views/verteiler/liste.vue
  yarn.lock
Labels: enhancement

#93 Release 0.1.6 oder 0.2.0
  docs/.vuepress/config.js
  electron/package.json
  electron/src/main/main.dev.js
  electron/src/main/main.js
  electron/yarn.lock
  package.json
  public/index.html
  public/style.css
  src/App.vue
  src/Login.vue
  src/baseComponents/reloader.ts
  src/graphql/index.ts
  src/main.ts
  src/plugins/auth.ts
  src/plugins/design/vuetify.ts
  src/plugins/formConfig/index.ts
  src/plugins/lesezeichen/addLesezeichen.vue
  src/plugins/lesezeichen/lesezeichen.ts
  src/plugins/lesezeichen/showLesezeichen.vue
  src/plugins/lib/buttons/router-back.ts
  src/plugins/lib/componentLib.ts
  src/plugins/lib/design/table.vue
  src/plugins/lib/formElements/formDialog/form.ts
  src/plugins/lib/password.vue
  src/plugins/lib_extension/componentLib_extension.ts
  src/plugins/router/router.ts
  src/plugins/router/routes/index.ts
  src/plugins/router/routes/router.vue
  src/plugins/widgets/index.ts
  src/plugins/widgets/widgetElement.vue
  src/plugins/widgets/widgets/alert.vue
  src/plugins/widgets/widgets/losungen.vue
  src/plugins/wrapper.vue
  src/plugins/xButton/btn.vue
  src/plugins/xButton/logic.ts
  src/views/Admin.vue
  src/views/Drucken.vue
  src/views/Home.vue
  src/views/Impressum.vue
  src/views/arbeitskreise/details.vue
  src/views/arbeitskreise/liste.vue
  src/views/personen/details.vue
  src/views/personen/liste.vue
  src/views/unterkünfte/details.vue
  src/views/veranstaltungen/details.vue
  src/views/verteiler/details.vue
  src/views/verteiler/liste.vue
  yarn.lock
Labels: release

#106 fix error at JSON parsing function
  src/plugins/lesezeichen/addLesezeichen.vue
  src/plugins/lesezeichen/lesezeichen.ts
Labels: bug

#109 Icons-Update
  src/App.vue
  src/plugins/config/nav.config.ts
  src/plugins/lesezeichen/showLesezeichen.vue
  src/views/arbeitskreise/details.vue
  src/views/personen/details.vue
  src/views/personen/liste.vue
  src/views/unterkünfte/details.vue
Labels: enhancement
