Repository EC-Nordbund/ec-verwaltungs-app, pull requests merged in 2018-06, with the labels that each got.

#21 Personen stamm
  .graphqlconfig
  .tmp/.gitkeep
  .travis.yml
  appveyor.yml
  package.json
  src/App.vue
  src/views/personen/details.vue
Labels: enhancement

#28 Widget settings
  electron/package.json
  electron/yarn.lock
  package.json
  public/index.html
  public/style.css
  src/App.vue
  src/Login.vue
  src/baseComponents/reloader.ts
  src/main.ts
  src/plugins/auth.ts
  src/plugins/eventbus.ts
  src/plugins/lib/formElements/formDialog/element.ts
  src/plugins/lib/formElements/formDialog/form.ts
  src/plugins/lib/formElements/inputs/radio.ts
  src/plugins/lib_extension/radioGroups/type.ts
  src/plugins/lib_extension/selects/akSelect.ts
  src/plugins/router/routeHandler.ts
  src/plugins/widgets/index.ts
  src/plugins/widgets/widgetContainer.vue
  src/plugins/widgets/widgetContainerSettings.vue
  src/plugins/widgets/widgetElementSettings.vue
  src/plugins/widgets/widgetTab.vue
  src/plugins/widgets/widgetTabSettings.vue
  src/plugins/widgets/widgets/losungen.vue
  src/views/Home.vue
  src/views/Impressum.vue
  src/views/anmeldungen/details.vue
  src/views/personen/details.vue
  vue.config.js
  yarn.lock
Labels: enhancement

#25 Release 0.1.3
  electron/package.json
  electron/src/main/main.dev.js
  electron/src/main/main.js
  electron/yarn.lock
  package.json
  public/index.html
  public/style.css
  src/App.vue
  src/Login.vue
  src/baseComponents/reloader.ts
  src/main.ts
  src/plugins/auth.ts
  src/plugins/config/nav.config.ts
  src/plugins/design/theme-directives.ts
  src/plugins/design/theme.ts
  src/plugins/eventbus.ts
  src/plugins/lib/buttons/add.ts
  src/plugins/lib/formElements/formDialog/element.ts
  src/plugins/lib/formElements/formDialog/form.ts
  src/plugins/lib/formElements/inputs/radio.ts
  src/plugins/lib_extension/radioGroups/type.ts
  src/plugins/lib_extension/selects/akSelect.ts
  src/plugins/router/routeHandler.ts
  src/plugins/updateChecker.ts
  src/plugins/widgets/index.ts
  src/plugins/widgets/widgetContainer.vue
  src/plugins/widgets/widgetContainerSettings.vue
  src/plugins/widgets/widgetElementSettings.vue
  src/plugins/widgets/widgetTab.vue
  src/plugins/widgets/widgetTabSettings.vue
  src/plugins/widgets/widgets/losungen.vue
  src/views/Home.vue
  src/views/Impressum.vue
  src/views/anmeldungen/details.vue
  src/views/personen/details.vue
  vue.config.js
  yarn.lock
Labels: bug, enhancement, help wanted

#31 Update version
  electron/package.json
  package.json
Labels: enhancement

#46 Merge Master back in DEV
  src/plugins/updateChecker.ts
Labels: help wanted

#43 remove ZIP from Build fix #40
  electron/package.json
  electron/yarn.lock
Labels: enhancement

#33 move to vuetify 1.1-rc fix #27
  package.json
  src/plugins/lib/formElements/selects/select.ts
  src/plugins/lib_extension/selects/akSelect.ts
  src/plugins/lib_extension/selects/personSelect.ts
  src/plugins/lib_extension/selects/verteilerSelect.ts
  src/views/personen/details.vue
  yarn.lock
Labels: bug, enhancement

#44 update Auskunftsrecht fix #42 + Hilfe in neuem Fenster
  src/App.vue
  src/plugins/config/nav.config.ts
  src/plugins/router/routes/index.ts
  src/views/Help.vue
  src/views/personen/details.vue
Labels: enhancement, good first issue

#48 Refactor
  electron/yarn.lock
  package.json
  src/baseComponents/reloader.ts
  src/plugins/auth.ts
  src/plugins/design/theme.ts
  src/plugins/electron.ts
  src/plugins/eventbus.ts
  src/plugins/lib/buttons/add.ts
  src/plugins/lib/buttons/icon-btn.ts
  src/plugins/lib/buttons/router-back.ts
  src/plugins/lib/componentLib.ts
  src/plugins/lib/design/headline.ts
  src/plugins/lib/design/list.ts
  src/plugins/lib/design/table.vue
  src/plugins/lib/formElements/formDialog/element.ts
  src/plugins/lib/formElements/formDialog/form.ts
  src/plugins/lib/formElements/inputs/radio.ts
  src/plugins/lib/formElements/inputs/switch.ts
  src/plugins/lib_extension/radioGroups/geschlecht.ts
  src/plugins/lib_extension/radioGroups/position.ts
  src/plugins/lib_extension/radioGroups/type.ts
  src/plugins/lib_extension/selects/akSelect.ts
  src/plugins/lib_extension/selects/personSelect.ts
  src/plugins/lib_extension/selects/verteilerSelect.ts
  src/plugins/querryError.ts
  src/plugins/router/routeHandler.ts
  src/plugins/settings.ts
  src/plugins/updateChecker.ts
  src/plugins/version/version.d.ts
  src/plugins/version/version.js
  src/plugins/widgets/index.ts
  src/plugins/widgets/types.ts
  src/plugins/widgets/widgets/index.ts
  src/views/personen/details.vue
  yarn.lock
Labels: enhancement, good first issue

#51 Lazy filter
  package.json
  src/plugins/lib/design/table.vue
  yarn.lock
Labels: enhancement

#56 Add icon
  electron/src/main/main.js
  public/ec-logo-128.png
  public/ec-logo-16.png
  public/ec-logo-256.png
  public/ec-logo-512.png
  src/App.vue
  src/Login.vue
  src/assets/logo.png
  src/views/personen/details.vue
Labels: enhancement

#58 edit + add Person Fertig
  src/views/personen/details.vue
  src/views/personen/liste.vue
Labels: enhancement

#59 Veranstaltung Datils-Design
  dev.bat
  dev.sh
  package.json
  src/plugins/lib/design/list.ts
  src/plugins/widgets/widgetContainer.vue
  src/views/veranstaltungen/details.vue
  src/views/veranstaltungen/liste.vue
  updateVersion.js
  yarn.lock
Labels: bug, enhancement
